### ISSUE TITLE
blockstack-profiles version

### ISSUE THREAD

**Issue by elmurci** [blockstack-packages/blockstack.js-old#3]
should it be set to ^0.3.6?

otherwise the examples in the blockstack-profile docs won't be compatible with 0.2.1...

**Comment by muneeb-ali** [comment]
@elmurci Thanks for starting the issue. Including @shea256 in the conversation.

**Comment by larrysalibra** [comment]
Thanks again @elmurci for bringing this up. `blockstack-profiles` is now included in `blockstack.js` so I'm going to close out this issue.
