### ISSUE TITLE
Dependencies referenced via ssh break npm install

### ISSUE THREAD

**Issue by larrysalibra** [blockstack-packages/blockstack.js-old#4]
From: https://github.com/blockstack/blockstack-profiles-js/issues/17

We need to bump the version of `blockstack-keychains` to one that doesn't include dependencies via ssh. In Portal, we use `0.0.8`.

**Comment by larrysalibra** [comment]
<img width="361" alt="screen shot 2017-03-06 at 8 37 31 pm" src="https://cloud.githubusercontent.com/assets/597182/23610230/cd0aa824-02ac-11e7-9c32-3376e49b4f16.png">

@shea256 ^^ same problem (blockstack-keychains 0.0.4 has dependencies included via ssh) . I'll fix it if you give me access to this repo. :-)

**Comment by shea256** [comment]
@larrysalibra Just added you.
